### ISSUE TITLE
Crash choix d'item sur develop

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1189]
Le bot crash entièrement quand on essaie de choisir quel item remplacer à la réception d'un autre
Du coup faut avoir au moins 3 slots remplis et obtenir un item
![image](https://user-images.githubusercontent.com/60353007/177856202-93567acb-7d15-4d60-8e84-bffc2bb34b40.png) 

Ma première impression est que ça arrive que quand il y a 1 seul joueur bloqué mais c'est pas le cas, j'ai testé
C'est pas non plus que le joueur est pas bloqué d'ailleurs, et tous les autres déblocages testés marchent

...\dist\src\core\bot\ipc\IPCServer.js:9
    blockedPlayers.set(discordId, blockedPlayers.get(discordId).filter(v => v.reason !== reason));

TypeError: Cannot read properties of undefined (reading 'filter')
    at removeBlockedReason (...\dist\src\core\bot\ipc\IPCServer.js:9:64)
    at ...\dist\src\core\bot\ipc\IPCServer.js:27:9
    at Server.<anonymous> (...\node_modules\node-ipc\node-ipc.cjs:543:9)
    at Server.emit [as publish] (...\node_modules\node-ipc\node-ipc.cjs:603:37)
    at Server.gotData (...\node_modules\node-ipc\node-ipc.cjs:912:10)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by Pietagorh** [comment]
Ah et le fait de refuser l'item dans cette configuration fait pas crash
