### ISSUE TITLE
À vérifier avant la maj

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1234]
- [ ] est-ce que les changements apportés par ce commit sont aussi sur develop ?  https://github.com/DraftBot-A-Discord-Adventure/DraftBot/commit/7f17692f39898feaf1055c16a9e6d78d1fa835b3

**Comment by Pietagorh** [comment]
Ceux par rapport passage à discord 13.6.0 oui, les DMs marchent mais faudrait vérifier si ça marche pour la fin du tw et les votes

**Comment by BastLast** [comment]
j'ai fait une branche (cf pr #1235 ) qui permet de tester ça

**Comment by Pietagorh** [comment]
Tout semble marcher sauf les votes

ça me fait ça quand j'fais le test fakevote
ReferenceError: __awaiter is not defined
at eval (eval at _eval (C:\Users\solal\OneDrive\Bureau\Code\DraftBot\node_modules\discord.js\src\client\Client.js:538:12), :1:23)
at eval (eval at _eval (C:\Users\solal\OneDrive\Bureau\Code\DraftBot\node_modules\discord.js\src\client\Client.js:538:12), :23:16)
at Client._eval (C:\Users\solal\OneDrive\Bureau\Code\DraftBot\node_modules\discord.js\src\client\Client.js:538:12)
at ShardClientUtil._handleMessage (C:\Users\solal\OneDrive\Bureau\Code\DraftBot\node_modules\discord.js\src\sharding\ShardClientUtil.js:189:82)
at process.emit (node:events:402:35)
at emit (node:internal/child_process:915:12)
at processTicksAndRejections (node:internal/process/task_queues:84:21)

**Comment by BastLast** [comment]
Check le commit de nysvaa jai du faire de la merde en le récupérant

**Comment by Pietagorh** [comment]
Yup ça marche maintenant
