### ISSUE TITLE
Gd peut crash

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1275]
Faut qu'je teste tous les gds du coup oof

**Comment by Pietagorh** [comment]
Ça semble être lié à un gain d'argent
![Screenshot_20220723_131259.jpg](https://user-images.githubusercontent.com/60353007/180603253-839f84ea-0907-4204-a2a2-e7c2e3d7124d.jpg)

**Comment by Pietagorh** [comment]
En fait c'est juste qu'il faut mettre un deferReply (j'imagine que parfois check tous les membres peut faire perdre pas mal de temps) (c'est arrivé au moins 4 fois de ce que je sais)
[2022/07/23 11:11:42] DiscordAPIError: Unknown interaction
    at RequestHandler.execute (/home/draftbot/DraftBot-A-Discord-Adventure/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/draftbot/DraftBot-A-Discord-Adventure/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async CommandInteraction.reply (/home/draftbot/DraftBot-A-Discord-Adventure/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:99:5)
