### ISSUE TITLE
[BUG]: DiscordAPIError: Unknown Member

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1302]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

Faudrait sûrement rajouter un await interaction.member.fetch() juste au début du command handler pour éviter cette erreur

DiscordAPIError: Unknown Member
    at RequestHandler.execute (/home/draftbot/DraftBot-A-Discord-Adventure/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/draftbot/DraftBot-A-Discord-Adventure/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async GuildMemberManager._fetchSingle (/home/draftbot/DraftBot-A-Discord-Adventure/node_modules/discord.js/src/managers/GuildMemberManager.js:407:18)

### Reproduction du bug.

C'est plus ou moins aléatoire imo

### Dans quelle condition le bug a-t-il été trouvé ?

Sur le serveur officiel du bot avec le bot officiel.

**Comment by Pietagorh** [comment]
ça semble pas trop problématique mais sur la shard 0 c'est arrivé genre 25 fois en 2 jours

**Comment by BastLast** [comment]
Ok ça osef de le faire en 3.0.0.c je decale

**Comment by BastLast** [comment]
ça serait bien que ça soit analysé ce truc

**Comment by romain22222** [comment]
From gpt :

Problèmes de cache : Parfois, les bibliothèques Discord.js (ou d'autres bibliothèques similaires) peuvent avoir des problèmes de mise en cache. Vous pouvez essayer de vider le cache du bot pour voir si cela résout le problème.

Latence du bot : Si le bot est en train de traiter de nombreuses demandes en même temps, il pourrait ne pas être en mesure de récupérer les informations sur les membres aussi rapidement qu'il le faudrait.

**Comment by BastLast** [comment]
rien d'utile, mais le seul moment ou on lis interaction.member c ici 
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/38099970/c4f8df61-d0d9-45b1-af21-c604af67119c)
du coup jvais check si juste changer ce truc pr un truc plus clean ça change le truc

**Comment by BastLast** [comment]
j'ai rien dit ya pleins d'endroit ou ya member qui est utilisé faudrait determiner lequel est responsable de ces logs

**Comment by BastLast** [comment]
je close car fixé en v5, en tout cas je l'ai plus jamais vu en v5
