### ISSUE TITLE
[BUG]: double mini event 

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1442]
### Description du bug.

![image](https://user-images.githubusercontent.com/38099970/193358085-acd5533f-d9ac-4ba6-b305-afe1f058d83f.png)

ça a été fait sans spammer vite donc... 

```
Error
    at Query.run (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\dialects\mariadb\query.js:53:25)
    at C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\sequelize.js:311:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MySQLQueryInterface.insert (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)
    at async PlayerSmallEvent.save (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\model.js:2432:35) {
  name: 'SequelizeUniqueConstraintError',
  errors: [
    ValidationErrorItem {
      message: 'PRIMARY must be unique',
      type: 'unique violation',
      path: 'PRIMARY',
      value: '0',
      origin: 'DB',
      instance: [PlayerSmallEvent],
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    }
  ],
  parent: SqlError: (conn=614, no: 1062, SQLState: 23000) Duplicate entry '0' for key 'PRIMARY'
  sql: INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?); - parameters:[8,'class',1664572782432,'2022-09-30 21:19:42.432','2022-09-30 21:19:16.000']
      at Object.module.exports.createError (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\misc\errors.js:57:10)
      at PacketNodeEncoded.readError (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet.js:586:19)
      at Query.readResponsePacket (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\cmd\parser.js:52:28)
      at PacketInputStream.receivePacketBasic (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet-input-stream.js:76:9)
      at PacketInputStream.onData (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet-input-stream.js:138:20)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    text: "Duplicate entry '0' for key 'PRIMARY'",
    sql: 'INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?);',
    fatal: false,
    errno: 1062,
    sqlState: '23000',
    code: 'ER_DUP_ENTRY',
    parameters: [
      8,
      'class',
      1664572782432,
      '2022-09-30 21:19:42.432',
      '2022-09-30 21:19:16.000'
    ]
  },
  original: SqlError: (conn=614, no: 1062, SQLState: 23000) Duplicate entry '0' for key 'PRIMARY'
  sql: INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?); - parameters:[8,'class',1664572782432,'2022-09-30 21:19:42.432','2022-09-30 21:19:16.000']
      at Object.module.exports.createError (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\misc\errors.js:57:10)
      at PacketNodeEncoded.readError (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet.js:586:19)
      at Query.readResponsePacket (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\cmd\parser.js:52:28)
      at PacketInputStream.receivePacketBasic (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet-input-stream.js:76:9)
      at PacketInputStream.onData (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet-input-stream.js:138:20)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    text: "Duplicate entry '0' for key 'PRIMARY'",
    sql: 'INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?);',
  },
  fields: { PRIMARY: '0' },
  sql: 'INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?);'
}
Error
    at Query.run (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\dialects\mariadb\query.js:53:25)
    at C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\sequelize.js:311:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MySQLQueryInterface.insert (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)
    at async PlayerSmallEvent.save (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\model.js:2432:35)
Error
    at Query.run (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\dialects\mariadb\query.js:53:25)
    at C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\sequelize.js:311:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MySQLQueryInterface.insert (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)
    at async PlayerSmallEvent.save (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\model.js:2432:35) {
  name: 'SequelizeUniqueConstraintError',
  errors: [
    ValidationErrorItem {
      message: 'PRIMARY must be unique',
      type: 'unique violation',
      path: 'PRIMARY',
      value: '0',
      origin: 'DB',
      instance: [PlayerSmallEvent],
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    }
  ],
  parent: SqlError: (conn=614, no: 1062, SQLState: 23000) Duplicate entry '0' for key 'PRIMARY'
  sql: INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?); - parameters:[8,'findPotions',1664572793639,'2022-09-30 21:19:53.640','2022-09-30 21:19:16.000']
      at Object.module.exports.createError (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\misc\errors.js:57:10)
      at PacketNodeEncoded.readError (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet.js:586:19)
      at Query.readResponsePacket (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\cmd\parser.js:52:28)
      at PacketInputStream.receivePacketBasic (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet-input-stream.js:76:9)
      at PacketInputStream.onData (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet-input-stream.js:138:20)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    text: "Duplicate entry '0' for key 'PRIMARY'",
    sql: 'INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?);',
    fatal: false,
    errno: 1062,
    sqlState: '23000',
    code: 'ER_DUP_ENTRY',
    parameters: [
      8,
      'findPotions',
      1664572793639,
      '2022-09-30 21:19:53.640',
      '2022-09-30 21:19:16.000'
    ]
  },
  original: SqlError: (conn=614, no: 1062, SQLState: 23000) Duplicate entry '0' for key 'PRIMARY'
  sql: INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?); - parameters:[8,'findPotions',1664572793639,'2022-09-30 21:19:53.640','2022-09-30 21:19:16.000']
      at Object.module.exports.createError (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\misc\errors.js:57:10)
      at PacketNodeEncoded.readError (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet.js:586:19)
      at Query.readResponsePacket (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\cmd\parser.js:52:28)
      at PacketInputStream.receivePacketBasic (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet-input-stream.js:76:9)
      at PacketInputStream.onData (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet-input-stream.js:138:20)
    fatal: false,
    errno: 1062,
    sqlState: '23000',
    code: 'ER_DUP_ENTRY',
    parameters: [
      8,
      'findPotions',
      1664572793639,
      '2022-09-30 21:19:53.640',
      '2022-09-30 21:19:16.000'
    ]
  },
  fields: { PRIMARY: '0' },
  sql: 'INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?);'
}
Error
    at Query.run (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\dialects\mariadb\query.js:53:25)
    at C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\sequelize.js:311:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MySQLQueryInterface.insert (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)
    at async PlayerSmallEvent.save (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\model.js:2432:35)
Error
    at Query.run (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\dialects\mariadb\query.js:53:25)
    at C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\sequelize.js:311:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MySQLQueryInterface.insert (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)
    at async PlayerSmallEvent.save (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\model.js:2432:35) {
  name: 'SequelizeUniqueConstraintError',
  errors: [
    ValidationErrorItem {
      message: 'PRIMARY must be unique',
      type: 'unique violation',
      path: 'PRIMARY',
      value: '0',
      origin: 'DB',
      instance: [PlayerSmallEvent],
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    }
  ],
  parent: SqlError: (conn=614, no: 1062, SQLState: 23000) Duplicate entry '0' for key 'PRIMARY'
  sql: INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?); - parameters:[8,'findPotions',1664572806778,'2022-09-30 21:20:06.778','2022-09-30 21:19:16.000']
      at Object.module.exports.createError (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\misc\errors.js:57:10)
      at PacketNodeEncoded.readError (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet.js:586:19)
      at Query.readResponsePacket (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\cmd\parser.js:52:28)
      at PacketInputStream.receivePacketBasic (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet-input-stream.js:76:9)
      at PacketInputStream.onData (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet-input-stream.js:138:20)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    text: "Duplicate entry '0' for key 'PRIMARY'",
    sql: 'INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?);',
    fatal: false,
    errno: 1062,
    sqlState: '23000',
    code: 'ER_DUP_ENTRY',
    parameters: [
      8,
      'findPotions',
      1664572806778,
      '2022-09-30 21:20:06.778',
      '2022-09-30 21:19:16.000'
    ]
  },
  original: SqlError: (conn=614, no: 1062, SQLState: 23000) Duplicate entry '0' for key 'PRIMARY'
  sql: INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?); - parameters:[8,'findPotions',1664572806778,'2022-09-30 21:20:06.778','2022-09-30 21:19:16.000']
      at Object.module.exports.createError (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\misc\errors.js:57:10)
      at PacketNodeEncoded.readError (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet.js:586:19)
      at Query.readResponsePacket (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\cmd\parser.js:52:28)
      at PacketInputStream.receivePacketBasic (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet-input-stream.js:76:9)
      at PacketInputStream.onData (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\mariadb\lib\io\packet-input-stream.js:138:20)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    text: "Duplicate entry '0' for key 'PRIMARY'",
    sql: 'INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?);',
    fatal: false,
    errno: 1062,
    sqlState: '23000',
    code: 'ER_DUP_ENTRY',
    parameters: [
      8,
      'findPotions',
      1664572806778,
      '2022-09-30 21:20:06.778',
      '2022-09-30 21:19:16.000'
    ]
  },
  fields: { PRIMARY: '0' },
  sql: 'INSERT INTO `player_small_events` (`id`,`playerId`,`eventType`,`time`,`updatedAt`,`createdAt`) VALUES (DEFAULT,?,?,?,?,?);'
}
Error
    at Query.run (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\dialects\mariadb\query.js:53:25)
    at C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\sequelize.js:311:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MySQLQueryInterface.insert (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)
    at async PlayerSmallEvent.save (C:\Users\Bastien\WebstormProjects\DraftBot\node_modules\sequelize\lib\model.js:2432:35)

```

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

test init puis lors du premier mini event crash. Le soucis a eu lieu sur une branche qui n'avais pas les changements du temps lié à la pr de @Feiryn  donc faut tenter de reproduire ce bug avec les infos que j'ai (càd pas assez) avant de pouvoir confirmer qu'il existe toujours

### Captures d'écran

![image](https://user-images.githubusercontent.com/38099970/193358418-3dd9d516-a1b2-43da-b6f1-c08258cba619.png)

**Comment by Feiryn** [comment]
Sans le test init y a le problème ?

**Comment by BastLast** [comment]
idk on testait pas ça on testait les conseils donc... yavais pas les changements de ta branche.

**Comment by BastLast** [comment]
je close ce truc en cannot reproduce, mais à surveiller
