### ISSUE TITLE
Retravailler le command manager

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1444]
après visite sur le serveur discord developpers, je pense que l'on doit encore améliorer le command manager.

- [x] On ne devrait pas supprimer et recréer une commande pour la modifier (or, je crois que c'est ce qu'on fait actuellement mais maybe je me trompe)
- [x] on a un soucis avec la suppression de commande : 
```
`Deleted command "reload"
DiscordAPIError[50035]: Invalid Form Body
command_id[NUMBER_TYPE_COERCE]: Value "reload" is not snowflake.
    at SequentialHandler.runRequest (/draftbot/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:293:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/draftbot/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
    at async REST.request (/draftbot/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
    at async ApplicationCommandManager.delete (/draftbot/node_modules/discord.js/src/managers/ApplicationCommandManager.js:220:5) {
  rawError: {
    code: 50035,
    errors: { command_id: [Object] },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'DELETE',
  url: 'https://discord.com/api/v10/applications/1018221697217863831/commands/reload',
  requestBody: { files: undefined, json: undefined }
}`
```
- [x] idéalement il faudrait tester à blinde parce que si on se fait ratelimit le bot officiel on a bien mais alors bien le seum parce que ça veut dire pas de bot pdt 24 h

**Comment by Feiryn** [comment]
Pour modif on fait un create c'est tout
Si ça arrive sur l'officiel on peut commenter les creations/suppressions de commandes en urgence
