### ISSUE TITLE
[BUG]: le /classement ne fonctionne plus 

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1451]
### Description du bug.

TypeError: playerSmallEvents is not iterable
    at Function.getLast (C:\Users\Bastien\WebstormProjects\DraftBot\dist\src\core\database\game\models\PlayerSmallEvent.js:28:34)
    at Function.<anonymous> (C:\Users\Bastien\WebstormProjects\DraftBot\dist\src\core\maps\TravelTime.js:46:73)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Bastien\WebstormProjects\DraftBot\dist\src\core\maps\TravelTime.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

/top

### Captures d'écran

![image](https://user-images.githubusercontent.com/38099970/193477711-c81c13b0-856d-4b74-a7ca-951969ebf2e3.png)
![Uploading image.png…]()

**Comment by BastLast** [comment]
ya un monde ou le bug https://github.com/DraftBot-A-Discord-Adventure/DraftBot/issues/824 est facile à résoudre en meme temps que ce soucis là, à vérifier
