### ISSUE TITLE
Le test guildreward marche plus

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1531]
### Description du bug.

TypeError: Cannot read properties of undefined (reading 'executeCommand')
    at Function.<anonymous> (C:\Users\Bastien\WebstormProjects\DraftBot\dist\src\commands\CommandsManager.js:106:60)
    at Generator.next (<anonymous>)
    at C:\Users\Bastien\WebstormProjects\DraftBot\dist\src\commands\CommandsManager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Bastien\WebstormProjects\DraftBot\dist\src\commands\CommandsManager.js:4:12)
    at Function.executeCommandWithParameters (C:\Users\Bastien\WebstormProjects\DraftBot\dist\src\commands\CommandsManager.js:105:16)
    at C:\Users\Bastien\WebstormProjects\DraftBot\dist\src\commands\admin\testCommands\Guild\GuildRewardTestCommand.js:43:45
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Bastien\WebstormProjects\DraftBot\dist\src\commands\admin\testCommands\Guild\GuildRewardTestCommand.js:5:58)
    at runMicrotasks (<anonymous>)

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

- /test guildreward <n'importe lequel>

### Captures d'écran

.

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by BastLast** [comment]
ça le fait à chaque fois ?

**Comment by Pietagorh** [comment]
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/master/src/commands/admin/testCommands/Guild/GuildRewardTestCommand.ts#L50 c'est ça j'pense
C'est executeCommand pas execute j'crois
