### ISSUE TITLE
Migration CRLF

### ISSUE THREAD

**Issue by niqore** [DraftBot-A-Discord-Adventure/DraftBot#162]
Add to readme that python is needed and maybe add a check when the bot starts if the command is available

**Comment by Nashoba24** [comment]
I figured out that the missing thing is not python, we must search what causes:
```
(node:25576) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: SQLITE_ERROR: no such table: armors
    at Query.formatError (F:\Downloads\DraftBot-A-Discord-Adventure-master\DraftBot-A-Discord-Adventure-master\node_modules\sequelize\lib\dialects\sqlite\query.js:422:16)
    at Query._handleQueryResponse (F:\Downloads\DraftBot-A-Discord-Adventure-master\DraftBot-A-Discord-Adventure-master\node_modules\sequelize\lib\dialects\sqlite\query.js:73:18)
    at afterExecute (F:\Downloads\DraftBot-A-Discord-Adventure-master\DraftBot-A-Discord-Adventure-master\node_modules\sequelize\lib\dialects\sqlite\query.js:250:31)
    at Statement.errBack (F:\Downloads\DraftBot-A-Discord-Adventure-master\DraftBot-A-Discord-Adventure-master\node_modules\sqlite3\lib\sqlite3.js:14:21)
(node:25576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Nashoba24** [comment]
L'erreur est causée quand on démarre une instance sur le code téléchargé en zip, depuis l'interface web

**Comment by BastLast** [comment]
déplacé pour la 2.1.0 car pas ultra urgent. De plus, @Nashoba24 et moi avons épuisé toutes nos idées pour la résolution de ce soucis

**Comment by BastLast** [comment]
close par erreur

**Comment by BastLast** [comment]
Pas de signalement depuis longtemps, close en attendant d'en savoir plus
