### ISSUE TITLE
Bug daily

### ISSUE THREAD

**Issue by niqore** [DraftBot-A-Discord-Adventure/DraftBot#662]
```
TypeError: Cannot read properties of null (reading 'valueOf')
    at /home/draftbot/DraftBot-A-Discord-Adventure/src/commands/player/DailyCommand.js:23:105
    at Generator.next (<anonymous>)
    at fulfilled (/home/draftbot/DraftBot-A-Discord-Adventure/dist/src/commands/player/DailyCommand.js:5:58)
```

**Comment by BastLast** [comment]
probablement corrigée dans le refactor, à réouvrir si jamais ca revient
